### ISSUE TITLE
Failing to build Silo 4.10.3 on Xcode 12 (clang 12)

### ISSUE THREAD

**Issue by herve-gross** [markcmiller86/silo-issues#210]
Hello,

I have had trouble compiling Silo with the latest installation of Apple's command line tools and Xcode versions (12).

Here is the type of errors I am getting (I have many similar errors):

```
In file included from ../../../silo/src/fpzip/write.cpp:3:
In file included from ../../../silo/src/fpzip/pcencoder.h:5:
../../../silo/src/fpzip/pcmap.h:17:13: error: expected member name or ';' after declaration specifiers
  typedef T DOMAIN;
  ~~~~~~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h:732:17: note: expanded from macro 'DOMAIN'
#define DOMAIN          1
                        ^
In file included from ../../../silo/src/fpzip/write.cpp:3:
In file included from ../../../silo/src/fpzip/pcencoder.h:5:
../../../silo/src/fpzip/pcmap.h:21:17: error: expected parameter declarator
  RANGE forward(DOMAIN d) const { return d >> shift; }
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h:732:17: note: expanded from macro 'DOMAIN'
#define DOMAIN          1
```

Some version information:

```
xcode-select -v
xcode-select version 2373
```

```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Any help would be much appreciated. Thanks!

**Comment by markcmiller86** [comment]
I need access to same system to help diagnose cause.

In meantime, unless you *absolutely need* fpzip, just configure with `--disable-fpzip` (and probably also `--disable-hzip`).

**Comment by markcmiller86** [comment]
@lindstro any idea why `DOMAIN` symbols in fpzip might be causing problems with compilation on macOS Catalina?

**Comment by lindstro** [comment]
I recall this being a fairly recent Mac thing.  I tackled this a while back and you should not be seeing this in fpzip 1.3.0.

**Comment by markcmiller86** [comment]
I've attached a patch file here...

[DOMAIN.patch.txt](https://github.com/markcmiller86/silo-issues/files/5360467/DOMAIN.patch.txt)

Can you pls try applying it and see if it fixes your issues.

**Comment by herve-gross** [comment]
Hi @markcmiller86 : thanks very much for the patch, I have applied it successfully and now Silo compiles without errors. Much appreciated!
